# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Compile and deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build 
        run: mvn clean compile
      - name: Test 
        env:
            TEST_API_KEY: ${{secrets.TEST_API_KEY}}
            TEST_MUDNAME: ${{secrets.TEST_MUDNAME}}
        run: mvn package
