name: Compile and deploy

on:
  # Runs on pushes targeting the default branch
  push:
    tags:
          - 'v*.*.*'  # Triggers for tags like v1.0.0, v2.1.3, etc.

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build 
        run: mvn clean compile
      - name: Test 
        env:
            TEST_API_KEY: ${{secrets.TEST_API_KEY}}
            TEST_MUDNAME: ${{secrets.TEST_MUDNAME}}
        run: mvn package
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
            tag_name: ${{ github.ref_name }}
            name: "Release ${{ steps.extract_version.outputs.VERSION }}"
        files: |
            target/*.jar
            generate_release_notes: true
            draft: false
            prerelease: false
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
