name: Release

on:
  # Runs on pushes targeting the default branch
  push:
    tags:
          - 'v*.*'  # Triggers for tags like v1.0.0, v2.1.3, etc.

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build 
        run: mvn clean compile
      - name: Test 
        env:
            TEST_API_KEY: ${{secrets.TEST_API_KEY}}
            TEST_MUDNAME: ${{secrets.TEST_MUDNAME}}
        run: mvn package
      - name: Get Maven project version
        id: project_version
        run: |
            VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
            echo "Project version: $VERSION"
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
            allowUpdates: true
            artifacts: target/*.jar
            generateReleaseNotes: true
            name: "${{ steps.extract_version.outputs.VERSION }}"
            replacesArtifacts: true
            tag: ${{ github.ref_name }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
